// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjJbBeLzZVjfiHTOI0COMAxo6O4qz0uBE',
    appId: '1:818500802753:web:a3bc9cfee231518448dc40',
    messagingSenderId: '818500802753',
    projectId: 'serious-a8b70',
    authDomain: 'serious-a8b70.firebaseapp.com',
    storageBucket: 'serious-a8b70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7e19etA0iX8h7r3rgnJh3af8UJTqRYuk',
    appId: '1:818500802753:android:e1e3c3728fffd34648dc40',
    messagingSenderId: '818500802753',
    projectId: 'serious-a8b70',
    storageBucket: 'serious-a8b70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBOlCpQvRV7Es-949xKmbtDf3Ps4f5Qcw',
    appId: '1:818500802753:ios:84482b15177debc248dc40',
    messagingSenderId: '818500802753',
    projectId: 'serious-a8b70',
    storageBucket: 'serious-a8b70.appspot.com',
    iosBundleId: 'com.example.serious',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBOlCpQvRV7Es-949xKmbtDf3Ps4f5Qcw',
    appId: '1:818500802753:ios:87f3f45aab75f12b48dc40',
    messagingSenderId: '818500802753',
    projectId: 'serious-a8b70',
    storageBucket: 'serious-a8b70.appspot.com',
    iosBundleId: 'com.example.serious.RunnerTests',
  );
}
